### ISSUE TITLE
  messageTemplate: 'file-not-found',

### ISSUE THREAD

**Issue by afifosh** [richardfuca/react-native-decompiler#103]
node ./out/main.js -i index.android.bundle -o ./output
Reading file...
Took 5.743898987770081ms
Parsing JS...
Took 105.41210100054741ms
Finding modules...
Took 136.55830001831055ms
Pre-parsing modules...
 ████████████████████████████████████████ 100% | ETA: 0s | 0/0
Took 9.281100004911423ms
Tagging...
 ████████████████████████████████████████ 100% | ETA: 0s | 0/0
Took 1.7289990186691284ms
Filtering out modules only depended on ignored modules...
Took 0.3035999834537506ms
Decompiling...
 ████████████████████████████████████████ 100% | ETA: 0s | 0/0
Took 1.1249990165233612ms
Generating code...
 ████████████████████████████████████████ 100% | ETA: 0s | 0/0
Took 1.2769989967346191ms
Saving...
 ████████████████████████████████████████ 100% | ETA: 0s | 0/0
Took 1.4063000082969666ms
Doing further cleanup with ESLint...
NoFilesFoundError: No files matching './output/*.js' were found.
    at FileEnumerator.iterateFiles (C:\Users\afifosh-OF\Desktop\react-native-decompiler-master\node_modules\eslint\lib\cli-engine\file-enumerator.js:308:27)
    at iterateFiles.next (<anonymous>)
    at CLIEngine.executeOnFiles (C:\Users\afifosh-OF\Desktop\react-native-decompiler-master\node_modules\eslint\lib\cli-engine\cli-engine.js:751:48)
    at ESLint.lintFiles (C:\Users\afifosh-OF\Desktop\react-native-decompiler-master\node_modules\eslint\lib\eslint\eslint.js:521:23)
    at main (C:\Users\afifosh-OF\Desktop\react-native-decompiler-master\out\main.js:268:38)
    at Object.<anonymous> (C:\Users\afifosh-OF\Desktop\react-native-decompiler-master\out\main.js:270:6)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14) {
  messageTemplate: 'file-not-found',
  messageData: { pattern: './output/*.js', globDisabled: false }
}

**Comment by richardfuca** [comment]
What are you trying to decompile?

**Comment by afifosh** [comment]
I am trying to decompile this app
https://play.google.com/store/apps/dev?id=8508918855182825204&hl=en_IE

**Comment by afifosh** [comment]
Thank you Richard you are genius.
