### ISSUE TITLE
Cannot compile TypeScript

### ISSUE THREAD

**Issue by Tatsh** [richardfuca/react-native-decompiler#196]
**Describe the bug**
Your description says to run `ts-node ./src/main.js` but I think you meant `main.ts`.

**To Reproduce**
1. Clone repo.
2. `npm i`
3. `ts-node ./src/main.js`

**Expected behavior**
Should build.

**Actual behavior**
Does not build.

**Additional context**
```
TSError: ⨯ Unable to compile TypeScript:
src/plugin.ts:63:32 - error TS2557: Expected at least 1 arguments, but got 0 or more.

63     debug(this.getDebugName())(...args);
                                  ~~~~~~~

  node_modules/@types/debug/index.d.ts:40:10
    40         (formatter: any, ...args: any[]): void;
                ~~~~~~~~~~~~~~
    An argument for 'formatter' was not provided.

    at createTSError (/home/tatsh/.node/lib/node_modules/ts-node/src/index.ts:587:12)
    at reportTSError (/home/tatsh/.node/lib/node_modules/ts-node/src/index.ts:591:19)
    at getOutput (/home/tatsh/.node/lib/node_modules/ts-node/src/index.ts:921:36)
    at Object.compile (/home/tatsh/.node/lib/node_modules/ts-node/src/index.ts:1189:32)
    at Module.m._compile (/home/tatsh/.node/lib/node_modules/ts-node/src/index.ts:1295:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .ts] (/home/tatsh/.node/lib/node_modules/ts-node/src/index.ts:1298:12)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
```

I forced this to build with some not-so-nice fixes for now, mainly casting to unknown and then to the correct type.

**Comment by richardfuca** [comment]
Thanks for the report, there is a new version coming out soon that will fix this

**Comment by sakarisson** [comment]
@Tatsh could you please share the steps you took for the workaround? :)

**Comment by KartikSoneji** [comment]
@Sakarisson Here is the patch I used

You should be able to apply it directly with [`git apply`](https://git-scm.com/docs/git-apply)

```diff
diff --git a/src/decompilers/es6/importsToEs6.ts b/src/decompilers/es6/importsToEs6.ts
index d5290b6..316d50d 100644
--- a/src/decompilers/es6/importsToEs6.ts
+++ b/src/decompilers/es6/importsToEs6.ts
@@ -49,6 +49,7 @@ export default class ImportsToEs6 extends Plugin {
             },
           });
           const [newPath] = varDeclar.parentPath.insertBefore(t.importDeclaration([t.importDefaultSpecifier(varIdentifier)], path.node.arguments[0]));
+          // @ts-ignore
           newPath.scope.registerBinding('module', newPath);
           varDeclar.remove();
           return;
diff --git a/src/decompilers/evaluators/defaultInteropEvaluator.ts b/src/decompilers/evaluators/defaultInteropEvaluator.ts
index 568758b..4b303ae 100644
--- a/src/decompilers/evaluators/defaultInteropEvaluator.ts
+++ b/src/decompilers/evaluators/defaultInteropEvaluator.ts
@@ -22,8 +22,6 @@ import {
   isIdentifier,
 } from '@babel/types';
 import { Plugin } from '../../plugin';
-import Module from '../../module';
-import CmdArgs from '../../interfaces/cmdArgs';
 
 /**
  * Evaluates babel default interops
diff --git a/src/editors/converters/babelInlineConverters.ts b/src/editors/converters/babelInlineConverters.ts
index dba54c4..ec3d04b 100644
--- a/src/editors/converters/babelInlineConverters.ts
+++ b/src/editors/converters/babelInlineConverters.ts
@@ -97,6 +97,7 @@ export default class BabelInlineConverters extends Plugin {
     this.debugLog('removed inline babel interopRequireDefault inline:');
     this.debugLog(this.debugPathToCode(path));
 
+    // @ts-ignore
     this.mergeBindings(path, node.id.name, moduleSourcePath.node.id.name);
 
     path.scope.bindings[test.left.left.name].path.remove();
diff --git a/src/plugin.ts b/src/plugin.ts
index 04798e1..3993dcf 100644
--- a/src/plugin.ts
+++ b/src/plugin.ts
@@ -60,6 +60,7 @@ export abstract class Plugin {
 
   protected debugLog(...args: unknown[]): void {
     if (args.length === 0) throw new Error('no args');
+    // @ts-ignore
     debug(this.getDebugName())(...args);
   }
```

**Comment by ang-st** [comment]
@KartikSoneji worked like a charm thanks :)

**Comment by 4n4n4s** [comment]
@richardfuca can we apply this patch from @KartikSoneji?

**Comment by ronytesler** [comment]
I still have that error and the Readme still says .js and not .ts. It should be main.js?

**Comment by richardfuca** [comment]
Hi, sorry for the delay. This issue should now be fixed, and I've updated the instructions a bit to improve usage.

**Comment by Tatsh** [comment]
We still have an error @richardfuca. Latest master:

```
/home/tatsh/.node/lib/node_modules/ts-node/src/index.ts:750
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/decompilers/es6/importsToEs6.ts(52,51): error TS2345: Argument of type 'NodePath<ImportDeclaration>' is not assignable to parameter of type 'NodePath<Node>'.
  Type 'Node' is not assignable to type 'ImportDeclaration'.
    Type 'AnyTypeAnnotation' is missing the following properties from type 'ImportDeclaration': specifiers, source

    at createTSError (/home/tatsh/.node/lib/node_modules/ts-node/src/index.ts:750:12)
    at reportTSError (/home/tatsh/.node/lib/node_modules/ts-node/src/index.ts:754:19)
    at getOutput (/home/tatsh/.node/lib/node_modules/ts-node/src/index.ts:941:36)
    at Object.compile (/home/tatsh/.node/lib/node_modules/ts-node/src/index.ts:1243:30)
    at Module.m._compile (/home/tatsh/.node/lib/node_modules/ts-node/src/index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/home/tatsh/.node/lib/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  diagnosticText: "src/decompilers/es6/importsToEs6.ts(52,51): error TS2345: Argument of type 'NodePath<ImportDeclaration>' is not assignable to parameter of type 'NodePath<Node>'.\n" +
    "  Type 'Node' is not assignable to type 'ImportDeclaration'.\n" +
    "    Type 'AnyTypeAnnotation' is missing the following properties from type 'ImportDeclaration': specifiers, source\n",
  diagnosticCodes: [ 2345 ]
}
```

**Comment by richardfuca** [comment]
Can you please try deleting node modules and reinstalling?

**Comment by Tatsh** [comment]
Okay looks like it works after that.
