### ISSUE TITLE
Errors while building the code

### ISSUE THREAD

**Issue by Neolex-Security** [richardfuca/react-native-decompiler#83]
Hello,
I'm trying to run `yarn run build` but I get the following errors: 
```
yarn run v1.22.4
$ tsc
src/main.ts:18:35 - error TS2558: Expected 0 type arguments, but got 1.

18 const argValues = commandLineArgs<{ in: string, out: string, entry: number, performance: boolean, verbose: boolean, decompileIgnored: boolean, agressiveCache: boolean }>([
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/taggers/remappers/passthroughModuleRemapper.ts:21:110 - error TS2339: Property 'value' does not exist on type 'MemberExpression'.

21         const passthroughDependency = this.moduleList[this.module.dependencies[path.node.right?.arguments[0].value]];
                                                                                                                ~~~~~


Found 2 errors.

error Command failed with exit code 2.
```

Do you know any way to fix it ? 

Thank you

**Comment by richardfuca** [comment]
Hi,

I fixed the build, pull from master & reinstall and it should then work

**Comment by Mek7** [comment]
Hi,
I just downloaded the zip of master branch, freshly installed node+npm, ts-node and having the exact same problem.

`npx ts-node main.ts -i index.android.bundle -o aaa
npx: installed 8 in 1.816s
⨯ Unable to compile TypeScript:
main.ts:18:35 - error TS2558: Expected 0 type arguments, but got 1.

18 const argValues = commandLineArgs<{ in: string, out: string, entry: number, performance: boolean, verbose: boolean, decompileIgnored: boolean, agressiveCache: boolean }>([
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by richardfuca** [comment]
Current master is building without error. Did you run `npm i`? There's some types that are patched during install.

**Comment by Mek7** [comment]
Thank you, running npm i fixed the error. I think it would be great to describe in the readme how to actually use this decompiler. I didn't use node, npm, or typescript to run a standalone application yet so I don't know how to solve possible problems off my head.
Now the error is gone, but there is another error

`npx ts-node main.ts -i index.android.bundle -o aaa
npx: installed 8 in 1.891s
Unexpected token '?'`

**Comment by Mek7** [comment]
I installed ts-node and typescript globally (npm -g flag) and now the error is much more descriptive.

npx ts-node src/main.ts

```
D:\Downloads\react-native-decompiler-master\src\main.ts:53
const cacheFileName = `${argValues.out}/${argValues.entry ?? 'null'}.cache`;
                                                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Module.m._compile (C:\Users\Mek\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\Mek\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at main (C:\Users\Mek\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:225:14)
    at Object.<anonymous> (C:\Users\Mek\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:512:3)

```

**Comment by Mek7** [comment]
I googled a lot and found out that I have to use nodejs version 14 (had 12 installed as that was the 'recommended' one).
Now I got another error

```
D:\Downloads\react-native-decompiler-master>npx ts-node src/main.ts

D:\Downloads\react-native-decompiler-master\node_modules\fs-extra\lib\mkdirs\make-dir.js:17
    const pathHasInvalidWinCharacters = /[<>:"|?*]/.test(pth.replace(path.parse(pth).root, ''))
                                                             ^
TypeError: Cannot read property 'replace' of undefined
    at checkPath (D:\Downloads\react-native-decompiler-master\node_modules\fs-extra\lib\mkdirs\make-dir.js:17:62)
    at Object.module.exports.makeDirSync (D:\Downloads\react-native-decompiler-master\node_modules\fs-extra\lib\mkdirs\make-dir.js:95:3)
    at Object.<anonymous> (D:\Downloads\react-native-decompiler-master\src\main.ts:45:9)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Module.m._compile (C:\Users\Mek\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\Mek\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)

```

**Comment by Mek7** [comment]
Got it, the error was because I didn't specify the -o parameter. After specifying both -i and -o, it worked like a charm.
However, I was not able to decompile my index.android.bundle. This decompiler probably expects that it will be a JS file, but my file is a binary one. Please state this in the readme that binary files are not supported.
I'm out of luck :(

**Comment by richardfuca** [comment]
Thanks for the feedback, I'll update the docs
